FROM maxleiko/armhf-alpine-java:latest

RUN apk update && \
apk add ca-certificates && \
update-ca-certificates && \
wget https://github.com/INF2A/RPI-docker-cluster/raw/master/Docker/Apache%20tomcat/apache-tomcat-9.tar.gz && \
tar zxf apache-tomcat-9.tar.gz && \
rm apache-tomcat-9.tar.gz && \
mv apache-tomcat* tomcat && \

EXPOSE 8080
CMD ["/tomcat/bin/catalina.sh", "run"]
