FROM maxleiko/armhf-alpine-java:latest

RUN apk update && \
apk add ca-certificates && \
update-ca-certificates && \
wget https://github.com/INF2A/RPI-docker-cluster/raw/master/Docker/Apache%20tomcat/apache-tomcat-9.tar.gz && \
tar zxf apache-tomcat-9.tar.gz && \
rm apache-tomcat-9.tar.gz && \
mv apache-tomcat* tomcat && \

wget https://github.com/INF2A/RPI-docker-cluster/blob/master/Docker/Api%20files/calendarapi/calendarapi.war?raw=true && \
mv calendarapi.war /tomcat/webapps/ && \

wget https://raw.githubusercontent.com/INF2A/RPI-docker-cluster/master/Docker/Api%20files/calendarapi/server.xml && \
mv server.xml /tomcat/conf/server.xml && \
rm -rf  "/tmp/*" \
        "/var/cache/apk/*" && \

wget https://github.com/INF2A/RPI-docker-cluster/blob/master/Docker/Api%20files/calendarapi/StoredCredential?raw=true && \
mv StoredCredential /tomcat/bin/credentials/calendar-java-calendar/StoredCredential

EXPOSE 8081
CMD ["/tomcat/bin/catalina.sh", "run"]
