FROM maxleiko/armhf-alpine-java:latest

RUN apk update && \
apk add ca-certificates && \
update-ca-certificates && \
wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M20/bin/apache-tomcat-9.0.0.M20.tar.gz && \
tar zxf apache-tomcat-*.tar.gz && \
rm apache-tomcat-*.tar.gz && \
mv apache-tomcat* tomcat

ADD calendar.war /tomcat/webapps
ADD server.xml /tomcat/conf/server.xml

EXPOSE 8080
CMD ["/tomcat/bin/catalina.sh", "run"]
